name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: |
          mkdocs build --clean  # Сначала соберите сайт
      - run: mkdocs gh-deploy --force  # Выполните деплой
      - name: Update CNAME
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch
          git checkout gh-pages
          echo "viyar-docs.viyar.tech" > CNAME
          git add CNAME
          git commit -m "Update CNAME"
          git push origin gh-pages
